name: build-then-test
on: [push, workflow_dispatch]
jobs: 
  run-test:
    runs-on: ubuntu-latest
    env:
      A_MONGODB_PASSWORD: ${{secrets.A_MONGODB_PASSWORD}}
      A_MONGODB_USERNAME: ${{secrets.A_MONGODB_USERNAME}}
      A_MONGODB_DB_NAME: ${{secrets.A_MONGODB_DB_NAME}}
      A_FULL_HOST: 'localhost:3000'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: npm run test
