name: on-push
on: [push, workflow_dispatch]
jobs: 
  run-test:
    runs-on: ubuntu-latest
    env:
      A_FULL_HOST: localhost:3000
      A_MONGODB_PASSWORD: ${{secrets.A_MONGODB_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: npm run log-vars
